---
configure_dotfiles: true
configure_terminal: true
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
 - Mail
 - Safari
 - Maps
 - Photos
 - FaceTime
 - Calendar
 - Contacts
 - Reminders
 - Notes
 - Freeform
 - TV
 - Music
 - 'App Store'

dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

dotfiles_repo: git@github.com:asmadsen/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/src/github.com/asmadsen/dotfiles
dotfiles_repo_version: master # Replace with your default branch
dotfiles_files:
  - .zshrc
  - .gitconfig
  - .dnb.gitconfig
  - .gitignore

homebrew_installed_packages:
  - gh
  - go
  - grep
  - jq
  - tree
  - watch
  - xz

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - 1password-cli
  - arc
  - chromium
  - docker
  - jetbrains-toolbox
  - pocket-casts
  - raspberry-pi-imager
  - slack
  - spotify
  - vivaldi


# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []