---
configure_dotfiles: true
configure_macos: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
 - Mail
 - Safari
 - Maps
 - Photos
 - FaceTime
 - Calendar
 - Contacts
 - Reminders
 - Notes
 - Freeform
 - TV
 - Music
 - 'App Store'
# - Podcasts

dockitems_persist:
 - name: "Vivaldi"
   path: "/Applications/Vivaldi.app/"
   pos: 3

dotfiles_repo_accept_hostkey: true
dotfiles_repo: git@github.com:asmadsen/dotfiles.git
dotfiles_repo_local_destination: ~/src/github.com/asmadsen/dotfiles
dotfiles_repo_version: master # Replace with your default branch
dotfiles_files:
  - .zshrc
  - .gitconfig
  - .dnb.gitconfig
  - .gitignore
  - .macos
  - .config/oh-my-posh/config.toml

homebrew_installed_packages:
  - fzf
  - gh
  - go
  - grep
  - jq
  - tree
  - vim
  - watch
  - xz
  - ssh-copy-id
  - jandedobbeleer/oh-my-posh/oh-my-posh

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - ghostty
  - jetbrains-toolbox
  - kubecontext
  - pocket-casts
  - proton-mail
  - proton-pass
  - raspberry-pi-imager
  - slack
  - spotify
  - setapp
  - vivaldi

mas_installed_apps:
  - { id: 441258766, name: "Magnet" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409201541, name: "Pages" }
  - { id: 409203825, name: "Numbers" }
mas_uninstalled_apps:
  - { id: 408981434, name: "iMovie" }
  - { id: 682658836, name: "GarageBand" }
mas_email: ""
mas_password: ""

macos_script: "~/.macos --no-restart"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
