---
configure_dotfiles: true

dotfiles_repo: git@github.com:asmadsen/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/src/github.com/asmadsen/dotfiles
dotfiles_files:
  - .zshrc
  - .gitconfig
  - .dnb.gitconfig
  - .gitignore

homebrew_installed_packages:
  - awscli
  - deno
  - dive
  - gh
  - go
  - gradle
  - graphviz
  - grep
  - helm
  - jenv
  - jq
  - k6
  - kube-capacity
  - kubernetes-cli
  - kubeval
  - kustomize
  - prometheus
  - terrascan
  - openjdk
  - openjdk@11
  - openjdk@17
  - python@3.11
  - tfenv
  - thefuck
  - tree
  - watch
  - xz
  - yamllint

homebrew_cask_apps:
  - 1password
  - 1password-cli
  - arc
  - chromium
  - docker
  - google-chrome
  - iterm2
  - jetbrains-toolbox
  - kubecontext
  - logitech-presentation
  - pocket-casts
  - raspberry-pi-imager
  - slack
  - spotify
  - todoist
  - vivaldi
  - warp

homebrew_taps:
  - homebrew/core
  - homebrew/cask-fonts
  - robscott/tap # for kube-capacity